### ISSUE TITLE
Compatibilty with JavaScript

### ISSUE THREAD

**Issue by lemoer** [jow-/ucode#18]
I wonder how big the differences are between ucode and JavaScript. Will it be possible to write a library that runs in both the browser and ucode? Will it even be possible to take any library from npm and run it in ucode? Or is this just a language that is oriented to JavaScript but does not intend to provide any level of compatibility?

**Comment by jow-** [comment]
The ucode syntax closely resembles JavaScript syntax mainly to be able to reuse existing code intelligence and syntax highlighting in editors and IDEs. Theoretically it could be possible to write a library that is both runnable in a JavaScript runtime and ucode, but I suppose it will be complicated since the runtimes and standard library environments are completely different.

uCode does not aim to be JavaScript/ES5/ES6 compatible but it borrows syntax elements and most runtime behavior from it.

**Comment by lemoer** [comment]
Thank you.
