### ISSUE TITLE
'map' over 'int' giving incorrect results

### ISSUE THREAD

**Issue by efahl** [jow-/ucode#205]
This is a pretty odd one, applying `int` over an array gives `NaN`s on arbitrary values.  It doesn't seem to be position related or value related.  Applying a user function `x => int(x)` in place of built-in `int` works fine, giving expected results on all the cases I've tried (which was a lot, trying to deduce a pattern).

```
$ ucode -p 'map(["23", "05", "3", "1", "3"], int)'
[ 23, "NaN", "NaN", 1, 3 ]

$ ucode -p 'map(["23", "05", "3", "1", "-2"], int)'
[ 23, "NaN", "NaN", 1, -2 ]

$ ucode -p 'map(["23", "05", "3", "1", "3", "-7"], int)'
[ 23, "NaN", "NaN", 1, 3, "NaN" ]

$ ucode -p 'map(["23", "05", "3", "1", "3", "-7"], x => int(x))'
[ 23, 5, 3, 1, 3, -7 ]
```

Bug presents identically on
x86, ath79, mt7622
with ucode versions:
Version: 2023-11-07-a6e75e02-1
Version: 2024.05.09~0d823e70-r1

**Comment by efahl** [comment]
Oh, here's a twist.  It gives an incorrect value of 0 for "05" on this one, instead of `NaN`, but again the user function works properly.

```
$ ucode -p 'map(["23", "x", "05", "3", "1", "3", "-7"], int)'
[ 23, "NaN", 0, "NaN", 1, 3, "NaN" ]

$ ucode -p 'map(["23", "blah", "05", "3", "1", "3", "-7"], x => int(x))'
[ 23, "NaN", 5, 3, 1, 3, -7 ]
```

**Comment by jow-** [comment]
That's because `int()` takes an optional second (and undocumented as I just noticed) base parameter while the `map()` function invokes the per-item callback which three arguments each: the item itself, the index and the array being mapped, so given your sequences above, int gets invoked as:

- `int("23", 0, [...])`
- `int("x", 1, [...])`
- `int("05", 2, [...])` 
- `int("3", 3, [...])`
- `int("1", 4, [...])`
- `int("3", 5, [...])`
- `int("-7", 6, [...])`

This means that `map(..., int)` will most likely never yield sane results. Wrapping `int` into an arrow function to strip away the excess params makes it work, as you noticed.

The `int()` function will try to parse the leading portion of a string into an integer, ignoring an unsuitable remainder, so e.g. `int("1234", 3)` is parsed as `12` and `34` is excluded as trailing garbage since the digits do not fit base 3. In case `int()` cannot parse at least one digit, it'll return `NaN`.

**Comment by efahl** [comment]
Ok, so simply a documentation issue.  I recalled seeing the `fn` with three parameters values, found it on `filter`.

Would you like me to come up with a PR?

1) Add optional second parameter description on `int`.
2) Add `fn` description to `map`.
3) Add "bad" example of why `map(..., int)` doesn't work.
4) Add references in `map` and `filter` to each other mentioning that `fn` is the same on both.

**Comment by jow-** [comment]
Yes, that would be much appreciated if you could do a pr addressing all these points

**Comment by efahl** [comment]
How do you prefer PRs?  On a branch like we do with owrt/packages, or on master?
