### ISSUE TITLE
regexp: character class not working in set

### ISSUE THREAD

**Issue by efahl** [jow-/ucode#215]
Package: ucode
Version: 2024.06.18~4dd98370-r1
Depends: libc, libucode20230711
Platform: x86/64-generic SNAPSHOT

When I try to use the digits class `\d` in a character set, it doesn't match, but if I expand it manually, it does:
```
$ ucode -p 'version_code="r24012-d8dd03c46f"; match(version_code, /^r(\d+)-[\da-f]+$/i)'

$ ucode -p 'version_code="r24012-d8dd03c46f"; match(version_code, /^r(\d+)-[0-9a-f]+$/i)'
[ "r24012-d8dd03c46f", "24012" ]
```
Clearly the class works, as it matches in the capture group, but fails when added to a set.

**Comment by jow-** [comment]
Yes, this is a limitation of POSIX extended regular expressions. Outside character classes, ucode translates some well known macros manually into sets, see here: https://github.com/jow-/ucode/blob/master/lexer.c#L292

But inside bracket expressions this is not really possible by doing mere text substitutions since it is impossible to express negations this way, e.g. `[xy\d]` could be substituted with `[xy[:digit:]]` but `[xy\D]` cannot be substituted with `[xy^[:digit:]]` as it would match a literal `^` and the numbers `0-9` instead of everything except `0-9`.

Anyhow, the tl;dr version is that macros such as `\d`, `\D`, `\w` etc. are specific to Perl compatible regular expressions while ucode, for size reasons, utilizes POSIX extended regular expressions as supported by the underlying libc.

In your particular case, consider using `/^r(\d+)-[[:xdigit:]]+$/` instead.

**Comment by efahl** [comment]
Got it, thanks!
